version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/mdevilliers/dtree
    steps:
      - checkout
      - run: make lint
      - run: make all

workflows:
  version: 2
  all:
    jobs:
      - build
