version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/mdevilliers/dtree
    steps:
      - checkout
      - run: make get-build-deps
      - run: make megacheck
      - run: make all

workflows:
  version: 2
  all:
    jobs:
      - build
